# Generated by Django 3.0.4 on 2020-04-03 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200402_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='profile_pics', upload_to='profile_pics'),
        ),
    ]
