# Generated by Django 3.0.4 on 2020-04-13 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200413_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='img',
            field=models.ImageField(default='blog_img/default.jpg', upload_to='blog_img/'),
        ),
    ]
